32: refactor deleteNote to accept note id only
exallium/todoapp pull request #33
Opened 2017-03-02 16:25 UTC by jshvarts

All tests pass

2017-03-02 16:28 UTC, exallium requested changes

2017-03-02 16:28 UTC, exallium commented on app/src/test/kotlin/com/exallium/todoapp/repository/StubNoteMapperImplTest.kt
> +        testSubject.remove(newNote().id)
don't bother creating a new note, just feed it jibberish

2017-03-02 16:41 UTC, jshvarts commented on app/src/test/kotlin/com/exallium/todoapp/repository/StubNoteMapperImplTest.kt
> +        testSubject.remove(newNote().id)
done

2017-03-03 01:16 UTC, exallium approved these changes

2017-03-03 01:24 UTC, merged