24 create note impl
exallium/todoapp pull request #40
Opened 2017-03-04 17:50 UTC by jshvarts

You can view it in action at https://drive.google.com/open?id=0B-5eHbqh90ciMjBzSHF5b3Jna2M

My only concern is removing noteId state in `CreateNotePresenter`. Need ideas how to do it. Thanks

2017-03-04 17:52 UTC, jshvarts commented on app/src/main/kotlin/com/exallium/todoapp/createnote/CreateNotePresenter.kt
> +    var noteId: String = ""
need help removing this state used in setupSaveNoteSubscription()

2017-03-06 13:35 UTC, exallium requested changes

2017-03-06 13:35 UTC, exallium commented on app/src/main/kotlin/com/exallium/todoapp/createnote/CreateNoteModelImpl.kt
> +class CreateNoteModelImpl(private val repository: Repository) : CreateNoteModel {
Consider making repository extend createnotemodel

2017-03-06 14:51 UTC, jshvarts commented on app/src/main/kotlin/com/exallium/todoapp/createnote/CreateNoteModelImpl.kt
> +class CreateNoteModelImpl(private val repository: Repository) : CreateNoteModel {
New ticket created https://github.com/exallium/todoapp/issues/44

2017-03-08 17:18 UTC, exallium approved these changes

2017-03-08 21:27 UTC, merged