47: do not look up note detail for edit if it was done before
exallium/todoapp pull request #48
Opened 2017-03-08 03:42 UTC by jshvarts

This addresses extra unneeded lookups on configuration changes

2017-03-08 17:18 UTC, exallium requested changes
A few things I'd like feedback on

2017-03-08 17:18 UTC, exallium commented on app/src/main/kotlin/com/exallium/todoapp/editnote/EditNotePresenter.kt
> +        view.bodyTextChanges()
The only thing I think is really missing from kotlin is proper function references, like `model::validateNoteTitleText`, which'd really let you minimize and generify this method.

There are probably ways to get rid of the duplication here, but nothing exceedingly straightforward.

2017-03-08 17:18 UTC, exallium commented on app/src/main/kotlin/com/exallium/todoapp/editnote/EditNotePresenter.kt
> +                .map { model.validateNoteTitleText(view.getNewNoteTitle()) }
what is the value of `it` in this lambda?

2017-03-08 17:18 UTC, exallium commented on app/src/main/kotlin/com/exallium/todoapp/editnote/EditNotePresenter.kt
> +                .map { model.validateNoteBodyText(view.getNewNoteBody()) }
what is the value of `it` in this lambda?

2017-03-08 17:18 UTC, exallium commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:2.3.0'
nice.

2017-03-08 17:58 UTC, jshvarts commented on app/src/main/kotlin/com/exallium/todoapp/editnote/EditNotePresenter.kt
> +                .map { model.validateNoteBodyText(view.getNewNoteBody()) }
done

2017-03-08 17:58 UTC, jshvarts commented on app/src/main/kotlin/com/exallium/todoapp/editnote/EditNotePresenter.kt
> +                .map { model.validateNoteTitleText(view.getNewNoteTitle()) }
done

2017-03-08 21:55 UTC, exallium requested changes
I think we want to use `BindString`. good otherwise.

2017-03-08 21:55 UTC, exallium commented on app/src/main/kotlin/com/exallium/todoapp/editnote/EditNoteViewImpl.kt
> +        noteTitleEditText.error = resources!!.getString(R.string.invalid_note_title_error)
`@BindString` ?

2017-03-08 21:55 UTC, exallium commented on app/src/main/kotlin/com/exallium/todoapp/editnote/EditNoteViewImpl.kt
> +        noteBodyTextView.error = resources!!.getString(R.string.invalid_note_body_error)
`@BindString` ?

2017-03-08 21:55 UTC, exallium commented on app/src/test/kotlin/com/exallium/todoapp/editnote/EditNotePresenterTest.kt
> +
this seems like a weird spot for spaces

2017-03-09 02:33 UTC, jshvarts commented on app/src/main/kotlin/com/exallium/todoapp/editnote/EditNoteViewImpl.kt
> +        noteTitleEditText.error = resources!!.getString(R.string.invalid_note_title_error)
done

2017-03-09 02:37 UTC, jshvarts commented on app/src/test/kotlin/com/exallium/todoapp/editnote/EditNotePresenterTest.kt
> +
github complained http://stackoverflow.com/questions/5813311/no-newline-at-end-of-file

2017-03-09 02:41 UTC, jshvarts commented on app/src/main/kotlin/com/exallium/todoapp/editnote/EditNotePresenter.kt
> +        view.bodyTextChanges()
could you make a follow-up commit with how you'd improve it so I can learn from it?

2017-03-09 12:12 UTC, exallium commented on app/src/test/kotlin/com/exallium/todoapp/editnote/EditNotePresenterTest.kt
> +
=) ok

2017-03-09 12:13 UTC, exallium commented on app/src/main/kotlin/com/exallium/todoapp/editnote/EditNotePresenter.kt
> +        view.bodyTextChanges()
I'll do a commit which generifies this and let you see it, yeah.

2017-03-09 12:13 UTC, exallium approved these changes

2017-03-09 12:32 UTC, merged