34: implement swipe-to-delete on all notes screen
exallium/todoapp pull request #51
Opened 2017-03-17 02:35 UTC by jshvarts

Tests will follow after the this code is reviewed.

2017-03-17 13:34 UTC, exallium requested changes

2017-03-17 13:34 UTC, exallium commented on app/src/main/kotlin/com/exallium/todoapp/allnotes/AllNotesAdapter.kt
> +        override fun isLongPressDragEnabled(): Boolean {
`override fun isLongPressDragEnabled() = false`

2017-03-17 13:34 UTC, exallium commented on app/src/main/kotlin/com/exallium/todoapp/allnotes/AllNotesAdapter.kt
> +        override fun isItemViewSwipeEnabled(): Boolean {
`override fun isItemViewSwipeEnabled() = true`

2017-03-17 13:34 UTC, exallium commented on app/src/main/kotlin/com/exallium/todoapp/allnotes/AllNotesAdapter.kt
> +        override fun onMove(recyclerView: RecyclerView?, viewHolder: RecyclerView.ViewHolder?, target: RecyclerView.ViewHolder?): Boolean {
`= false`

2017-03-17 13:34 UTC, exallium commented on app/src/main/kotlin/com/exallium/todoapp/allnotes/AllNotesAdapter.kt
>      private var clickSubject = PublishSubject.create<Int>()
does this need to be a click subject? couldn't you return `itemView.clicks()` ?

2017-03-17 13:34 UTC, exallium commented on app/src/main/kotlin/com/exallium/todoapp/allnotes/AllNotesPresenter.kt
> +                .subscribe(object : Subscriber<Unit>() {
consider using subscribe({}, {}) method instead of creating this annonymous object

2017-03-17 15:38 UTC, jshvarts commented on app/src/main/kotlin/com/exallium/todoapp/allnotes/AllNotesAdapter.kt
> +        override fun isLongPressDragEnabled(): Boolean {
done

2017-03-17 15:38 UTC, jshvarts commented on app/src/main/kotlin/com/exallium/todoapp/allnotes/AllNotesAdapter.kt
> +        override fun isItemViewSwipeEnabled(): Boolean {
done

2017-03-17 15:38 UTC, jshvarts commented on app/src/main/kotlin/com/exallium/todoapp/allnotes/AllNotesAdapter.kt
> +        override fun onMove(recyclerView: RecyclerView?, viewHolder: RecyclerView.ViewHolder?, target: RecyclerView.ViewHolder?): Boolean {
done

2017-03-17 15:38 UTC, jshvarts commented on app/src/main/kotlin/com/exallium/todoapp/allnotes/AllNotesPresenter.kt
> +                .subscribe(object : Subscriber<Unit>() {
done

2017-03-17 15:39 UTC, jshvarts commented on app/src/main/kotlin/com/exallium/todoapp/allnotes/AllNotesAdapter.kt
>      private var clickSubject = PublishSubject.create<Int>()
not as simple to set up communication between viewholder and adapter

2017-03-17 17:26 UTC, exallium commented on app/src/main/kotlin/com/exallium/todoapp/allnotes/AllNotesAdapter.kt
>      private var clickSubject = PublishSubject.create<Int>()
Adapter gets view holder reference in onBindViewHolder, that should be enough I think.

2017-03-17 22:09 UTC, jshvarts commented on app/src/main/kotlin/com/exallium/todoapp/allnotes/AllNotesAdapter.kt
>      private var clickSubject = PublishSubject.create<Int>()
i need your help with this. clicks() returns Observable<Unit>. I'd need Observable<String>.

2017-03-18 01:56 UTC, exallium commented on app/src/main/kotlin/com/exallium/todoapp/allnotes/AllNotesAdapter.kt
>      private var clickSubject = PublishSubject.create<Int>()
`map` ? using `viewHolder.position`

2017-03-19 02:26 UTC, jshvarts commented on app/src/main/kotlin/com/exallium/todoapp/allnotes/AllNotesAdapter.kt
>      private var clickSubject = PublishSubject.create<Int>()
i am afraid i don't understand how to do it

2017-03-20 18:31 UTC, exallium commented on app/src/main/kotlin/com/exallium/todoapp/allnotes/AllNotesAdapter.kt
>      private var clickSubject = PublishSubject.create<Int>()
something like this inside view holder:

```
fun clicks() = itemView.clicks().filter { position == -1 }.map { adapterPosition }
```

position is the position in the view holder.  when a view is recycled, it's set to -1 (by recycler view, not by us)

adapterPosition is the view's position in the adapter's data model.

So, we return a chain that filters out any clicks that are somehow propagated by things off screen, and emit the adapter position of the object clicked.

We can then subscribe to this in onCreateViewHolder:

```
fun onCreateViewHolder(...) {
   val viewHolder = ViewHolder.create(...)
   compositeSubscription.add(viewHolder.clicks().subscribe(onClickFn))
}
```

2018-01-20 23:59 UTC, closed without merging