55: set up default values and remove with()
exallium/todoapp pull request #56
Opened 2017-03-23 13:42 UTC by jshvarts

val note = Note()
        Timber.d("note: " + note)
        Timber.d("empty string: " + Note.EMPTY_STRING)
        Timber.d("empty timestamp: " + Note.EMPTY_TIMESTAMP)
        Timber.d("copy: " + note.copy(id = "10", title = "new 10"))

prints:

note: Note(id=, title=, body=, created=0, updated=0)
empty string: 
empty timestamp: 0
copy: Note(id=10, title=new 10, body=, created=0, updated=0)

2017-03-23 14:11 UTC, exallium requested changes

2017-03-23 14:11 UTC, exallium commented on app/src/main/kotlin/com/exallium/todoapp/entities/Note.kt
> +        val EMPTY_TIMESTAMP = 0L
Technically 0L is a valid timestamp.  let's make this -1L

2017-03-23 14:11 UTC, exallium commented on app/src/main/kotlin/com/exallium/todoapp/entities/Note.kt
> -    fun with(id: String? = null,
=D

2017-03-23 14:25 UTC, jshvarts commented on app/src/main/kotlin/com/exallium/todoapp/entities/Note.kt
> +        val EMPTY_TIMESTAMP = 0L
done

2017-03-24 01:47 UTC, jshvarts commented on app/src/main/kotlin/com/exallium/todoapp/entities/Note.kt
> +        val EMPTY_TIMESTAMP = 0L
so the current validation i have checks if the field is not just empty but blank which is better than comparing to Note.EMPTY_STRING. unless i add several specific validation methods on Note all checking the same thing (empty string), my current validation is fine and the empty fields in the constructor are only used for something like firebase that requires no args constructor.

2018-01-20 23:59 UTC, closed without merging